apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-qzhkgt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-qzhkgt
    app.kubernetes.io/part-of: build-suite-positive-mc-qzxf
  name: go-component-qzhkgt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-qzhkgt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-qzhkgt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-qzvp-tenant/build-suite-positive-mc-qzxf/go-component-qzhkgt@sha256:ca83beb0c16bdd2bf3b8f7e6ff31cebc489e1a8de052e04d0bd40a0ca2d271bf
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
